Repository semsol/arc2, pull requests merged in 2020-03, with the labels that each got.

#137 Upgrade vendors, fix tests (prepare version 2.5)
  .gitignore
  .travis.yml
  README.md
  composer.json
  doc/branches.png
  doc/developer.md
  docker/Docker/arc2/Dockerfile
  docker/Docker/arc2/arc2.conf
  docker/Docker/arc2/arc2.sh
  docker/Docker/arc2/custom.ini
  docker/Makefile
  docker/docker-compose.yml-dist
  phpunit.xml
  src/ARC2/Store/Adapter/PDOAdapter.php
  store/ARC2_MemStore.php
  store/ARC2_RemoteStore.php
  store/ARC2_Store.php
  store/ARC2_StoreLoadQueryHandler.php
  store/ARC2_StoreSelectQueryHandler.php
  tests/ARC2_TestCase.php
  tests/db_adapter_depended/ARC2_ClassTest.php
  tests/db_adapter_depended/sparql_1_1_tests/AggregatesTest.php
  tests/db_adapter_depended/sparql_1_1_tests/ComplianceTest.php
  tests/db_adapter_depended/sparql_1_1_tests/ConstructTest.php
  tests/db_adapter_depended/sparql_1_1_tests/DropTest.php
  tests/db_adapter_depended/sparql_1_1_tests/SyntaxUpdate1Test.php
  tests/db_adapter_depended/src/ARC2/Store/Adapter/CachedPDOAdapterTest.php
  tests/db_adapter_depended/store/ARC2_StoreAskQueryHandlerTest.php
  tests/db_adapter_depended/store/ARC2_StoreInsertQueryHandlerTest.php
  tests/db_adapter_depended/store/ARC2_StoreTest.php
  tests/db_adapter_depended/store/query/AskQueryTest.php
  tests/db_adapter_depended/store/query/DeleteQueryTest.php
  tests/db_adapter_depended/store/query/DescribeQueryTest.php
  tests/db_adapter_depended/store/query/ErrorHandlingInQueriesTest.php
  tests/db_adapter_depended/store/query/InsertIntoQueryTest.php
  tests/db_adapter_depended/store/query/KnownNotWorkingSparqlQueriesTest.php
  tests/db_adapter_depended/store/query/LoadQueryTest.php
  tests/db_adapter_depended/store/query/SelectQueryTest.php
  tests/unit/ARC2_ClassTest.php
  tests/unit/ARC2_GraphTest.php
  tests/unit/ARC2_ReaderTest.php
  tests/unit/ARC2_getPreferredFormatTest.php
  tests/unit/src/ARC2/Store/Adapter/AbstractAdapterTest.php
  tests/unit/src/ARC2/Store/Adapter/AdapterFactoryTest.php
  tests/unit/src/ARC2/Store/Adapter/CachedPDOAdapterTest.php
  tests/unit/src/ARC2/Store/Adapter/PDOAdapterTest.php
  tests/unit/store/ARC2_StoreLoadQueryHandlerTest.php
  tests/unit/store/ARC2_StoreTest.php
Labels: enhancement, fix, store

#141 Add link to the documentation in README.md
  README.md
Labels: enhancement

#144 Travis adaptions to avoid failing tests based on misconfiguration or timeouts
  .travis/install-and-init-db.sh
Labels: fix

#142 Fixed store/ARC2_StoreEndpoint.php: $this has no property named $store
  .travis.yml
  store/ARC2_StoreEndpoint.php
  tests/unit/store/ARC2_StoreEndpointTest.php
Labels: enhancement, fix
